version: '2'
services:

 mariadb:
    image: 'bitnami/mariadb:latest'
    container_name: mariadb
    environment:
      #- MARIADB_ROOT_USER=root
      #- MARIADB_ROOT_PASSWORD=123456
      - ALLOW_EMPTY_PASSWORD=yes
      #- MARIADB_USER=bitnami
      #- MARIADB_DATABASE=123456
    volumes:
      - 'mariadb_data:/bitnami'
    ports:
      - "127.0.0.1:3306:3306"
 piwik:
  image: 'bitnami/piwik:latest'
  container_name: piwik
  ports:
   - "80:80"
  depends_on:
   - mariadb
   - fluentd
  logging:
    driver: "fluentd"
    options:
      fluentd-address: localhost:24224
      tag: httpd.access

 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
  container_name: elasticsearch
  environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - xpack.security.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536
      hard: 65536
  mem_limit: 2g
  cap_add:
    - IPC_LOCK
  volumes:
    - esdata1:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
  networks:
   - back-tier

 fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    logging:
        driver: "json-file"
        options:
            max-size: 100m
            max-file: "5"
    networks:
     - front-tier
     - back-tier

 kibana:
  image: kibana
  container_name: kibana
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200
  ports:
   - "5601:5601"
  links:
   - elasticsearch
  networks:
   - back-tier


volumes:
  esdata1:
    driver: local
  mariadb_data:
    driver: local
  piwik_data:
    driver: local

networks:
  front-tier:
  back-tier:
   driver: bridge

