version: '2'
services:
  jenkins:
    restart: always
    image: jenkins
    ports:
      - "83:8080"
      - "50000:50000"
    volumes:
      - 'data_jenkins:/var/jenkins_home'
volumes:
  data_jenkins:
    driver: local
