version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    restart: always
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:latest'
    restart: always
    ports:
      - '81:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  mediawiki:
    image: 'bitnami/mediawiki:latest'
    restart: always
    environment:
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '444:443'
    volumes:
      - 'mediawiki_data:/bitnami'
    depends_on:
      - mariadb
  piwik:
    image: 'bitnami/piwik:latest'
    restart: always
    ports:
      - '82:80'
      - '445:443'
    volumes:
      - 'piwik_data:/bitnami'
    depends_on:
      - mediawiki
  phabricator:
    image: 'bitnami/phabricator:latest'
    restart: always
    ports:
      - '83:80'
      - '446:443'
    volumes:
      - 'phabricator_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - PHABRICATOR_HOST=127.0.0.1
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your_email@gmail.com
      - SMTP_PASSWORD=your_password
  openmodelica-webbook:
    container_name: openmodelica-webbook
    restart: always
    image: smartkit/omwebbook
    ports:
      - '84:80'
  jenkins:
    restart: always
    image: jenkins
    ports:
      - "85:8080"
      - "50000:50000"
    volumes:
      - 'jenkins_data:/var/jenkins_home'
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  phabricator_data:
    driver: local
  mediawiki_data:
    driver: local
  piwik_data:
    driver: local
  jenkins_data:
    driver: local
