version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    container_name: mariadb
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=admin123
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'data_mariadb:/bitnami'
    ports:
      - '3306:3306'
volumes:
  data_mariadb:
    driver: local
