version: '2'
services:
  mediawiki:
    image: 'bitnami/mediawiki:latest'
    ports:
      - '82:80'
      - '443:443'
    volumes:
      - 'data_mediawiki:/bitnami'
    environment:
      # - MARIADB_HOST=mariadb
      # - MARIADB_PORT_NUMBER=3306
      # - MEDIAWIKI_DATABASE_USER=bn_mediawiki
      # - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mariadb
volumes:
  data_mediawiki:
    driver: local