version: '2'
services:
  phabricator:
    image: 'bitnami/phabricator:latest'
    ports:
      - '83:80'
      - '446:443'
    volumes:
      - 'phabricator_data:/bitnami'
volumes:
  phabricator_data:
    driver: local
