version: "2"

services:
  mariadb:
    image: 'mariadb:10.3'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=W2qgpsLtQt
    volumes:
      - '/data/xlpsystem/mariadb/:/var/lib/mysql'

  mediawiki:
    image: daocloud.io/weimar/xlp_mediawiki:20180820180437
    restart: always
    # environment:
    #   - MYSQL_USER=root
    #   - MYSQL_PASSWORD=W2qgpsLtQt
    ports:
      - 80:80
    volumes:
      # - '/data/xlpsystem/mediawiki_dev:/xlp_dev'
      - '/data/xlpsystem/mediawiki:/xlp_data'
    depends_on:
      - mariadb
      - matomo

  wordpress:
    image: daocloud.io/weimar/xlp_wordpress:20180820185725
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb
    ports:
      - 81:80
    volumes:
      - '/data/xlpsystem/wordpress:/var/www/html'
    depends_on:
      - mariadb
      - matomo

  matomo:
    image: daocloud.io/weimar/xlp_matomo:20180820163542
    restart: always
    ports:
      - 82:80
    volumes:
      - '/data/xlpsystem/matomo:/var/www/html'
    depends_on:
      - mariadb

  elasticsearch:
    image: daocloud.io/weimar/xlp_elasticsearch:20180822102938
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  kibana:
    image: daocloud.io/weimar/xlp_kibana:20180821233221
    ports:
      - 5601:5601
