version: "2"

services:
  mariadb:
    image: 'mariadb:10.3'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=W2qgpsLtQt
    volumes:
      - '/data/xlpsystem/mariadb/:/var/lib/mysql'

  mediawiki:
    image: daocloud.io/weimar/xlp_mediawiki:20180815224342
    restart: always
    # environment:
    #   - MYSQL_USER=root
    #   - MYSQL_PASSWORD=W2qgpsLtQt
    ports:
      - 20001:80
    volumes:
      # - '/data/xlpsystem/mediawiki_dev:/xlp_dev'
      - '/data/xlpsystem/mediawiki:/xlp_data'
    depends_on:
      - mariadb

  wordpress:
    image: daocloud.io/weimar/xlp_wordpress:20180816154427
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb
    ports:
      - 20002:80
    volumes:
      - '/data/xlpsystem/wordpress:/var/www/html'
    depends_on:
      - mariadb
