version: '2'
services:


# java-aggregator:
#   image: smartkit/eip-elk-spring-boot-mariadb
#   ports:
#    - "8080:8080"
#   links:
#    - logstash
#   networks:
#    - front-tier
 piwik:
    image: 'bitnami/piwik:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'piwik_data:/bitnami'
    depends_on:
      - mariadb
 mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - '127.0.0.0.1:3306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
#      - MARIADB_DATABASE=bitnami_piwik
    volumes:
      - 'mariadb_data:/bitnami'
#    volumes:
#        - ./database:/tmp/database
#    command: mysqld --init-file="/tmp/database/bitnami_piwik_20171222.sql"

 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
  container_name: elasticsearch
  environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - xpack.security.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536
      hard: 65536
  mem_limit: 2g
  cap_add:
    - IPC_LOCK
  volumes:
    - esdata1:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
  networks:
    - back-tier

 logstash:
  image: logstash
  container_name: logstash
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
   - ./src/main/logstash/config:/etc/logstash/conf.d
  ports:
   - "5000:5000"
  links:
   - elasticsearch
  networks:
   - front-tier
   - back-tier

 kibana:
  image: kibana
  container_name: kibana
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200
  ports:
   - "5601:5601"
  links:
   - elasticsearch
  networks:
   - back-tier


volumes:
  esdata1:
    driver: local
  mariadb_data:
    driver: local
  piwik_data:
    driver: local

networks:
  front-tier:
  back-tier:
   driver: bridge
